apiVersion: v1
kind: Service
metadata:
  name: app-file-management-database-postgres-service
spec:
  selector:
    app: app-file-management-database-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP