apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-process
  template:
    metadata:
      labels:
        app: file-process
    spec:
      containers:
        - name: file-process
          image: app-file-process:1.0.14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: aws-credentials