apiVersion: v1
kind: Service
metadata:
  name: app-file-process-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: app-file-process-lb
spec:
  type: LoadBalancer
  selector:
    app: app-file-process
  ports:
    - name: http
      port: 8080
      targetPort: 8080